ALTER TABLE employees MODIFY COLUMN name varchar NOT NULL;
CREATE TABLE `test2` (
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
